# Generated by Django 2.2.6 on 2019-10-31 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce_name', models.CharField(max_length=200)),
                ('sauce_description', models.CharField(max_length=200)),
                ('sauce_price', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('sale_price', models.IntegerField(default=0)),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Sauce')),
            ],
        ),
    ]
