# Generated by Django 2.2.6 on 2019-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OliveOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olive_name', models.CharField(max_length=200)),
                ('olive_description', models.CharField(max_length=200)),
                ('olive_image', models.CharField(max_length=200)),
                ('olive_price', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
