# Generated by Django 2.2.6 on 2019-11-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_number', models.CharField(max_length=200)),
            ],
        ),
    ]
