# Generated by Django 2.2.6 on 2019-12-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0003_auto_20191203_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.CharField(help_text='Your email', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text='John Doe', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=models.IntegerField(help_text='###-###-####'),
        ),
    ]
