# Generated by Django 2.2.6 on 2019-12-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0004_auto_20191203_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=models.CharField(max_length=200),
        ),
    ]
