# Generated by Django 2.2.6 on 2019-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0005_auto_20191203_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name='date created'),
        ),
    ]
