# Generated by Django 2.2.6 on 2019-12-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0006_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
    ]
