# Generated by Django 2.2.6 on 2019-12-04 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0007_auto_20191203_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 4, 1, 5, 10, 31384, tzinfo=utc), help_text='date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 4, 1, 5, 56, 449819, tzinfo=utc), help_text='date modified'),
            preserve_default=False,
        ),
    ]
