# Generated by Django 2.2.6 on 2019-12-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0008_auto_20191204_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='date created', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, help_text='date modified', null=True),
        ),
    ]
