# Generated by Django 2.2.6 on 2019-12-04 01:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0009_auto_20191204_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 1, 8, 10, 50408, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
