# Generated by Django 2.2.6 on 2019-12-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0012_order_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='olive_id',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=models.IntegerField(max_length=200),
        ),
    ]
