# Generated by Django 2.2.6 on 2019-12-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0013_auto_20191204_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='olive_id',
            field=models.IntegerField(null=True),
        ),
    ]
