# Generated by Django 2.2.6 on 2019-12-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0015_auto_20191204_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_number',
            new_name='number',
        ),
    ]
