# Generated by Django 2.2.6 on 2019-12-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0018_auto_20191204_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Zip_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
