# Generated by Django 2.2.6 on 2019-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olive', '0019_auto_20191204_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Zip_code',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
